version: '3.3'

services:
  db:
    image: postgres
    container_name: postgres 
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wordpress
      - POSTGRES_PASSWORD=wordpress
      - POSTGRES_DB=perfdata
  performancedatastorage:
    image: performancedatastorage:latest
    container_name: performancedatastorage
    restart: always
    environment:
      MYSQL_HOST: db
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    volumes:
      - ./:/mosquitto/config/
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  requestgenerator:
    image: requestgenerator:latest
    container_name: requestgenerator
    restart: always
    volumes:
      - ../pdgf:/pdgf
    links:
      - mosquitto:users

  configui:
    image: configui:latest
    restart: always
    container_name: configui
    ports:
      - 3000:80

volumes:
  pg_data: {}
  mosquitto_data: {}
  mosquitto_log: {}

