version: '3.3'
services:
  db:
    image: postgres
    container_name: postgres 
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wordpress
      - POSTGRES_PASSWORD=wordpress
      - POSTGRES_DB=perfdata
    ports:
      - 5432:5432
  performancedatastorage:
    image: performancedatastorage:latest
    container_name: performancedatastorage
    restart: always
    environment:
      MYSQL_HOST: db
    ports:
      - 6080:6080
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    ports:
      - 9001:9001
    volumes:
      - ./:/mosquitto/config/
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  requestgenerator:
    image: requestgenerator:latest
    container_name: requestgenerator
    restart: always
    volumes:
      - ../pdgf:/pdgf
      - ./pdgf-output:/output
    ports:
      - 8080:8080
    environment:
            - EXTRA_ARGUMENTS=--location http://localhost:8080 --bufferSize 1 --alternative-output-dir /output
    extra_hosts:
      - "users:172.22.17.255"
      - "posts:172.22.17.255"
      - "search:172.22.17.255"

  configui:
    image: configui:latest
    restart: always
    container_name: configui
    ports:
      - 3000:80

volumes:
  pg_data: {}
  mosquitto_data: {}
  mosquitto_log: {}

