#
# WALT - A realistic load generator for web applications.
#
# Copyright 2019-2020 Eric Ackermann <eric.ackermann@student.hpi.de>, Hendrik
# Bomhardt <hendrik.bomhardt@student.hpi.de>, Benito Buchheim
# <benito.buchheim@student.hpi.de>, Juergen Schlossbauer
# <juergen.schlossbauer@student.hpi.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.3'
services:
  db:
    image: postgres
    container_name: postgres 
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wordpress
      - POSTGRES_PASSWORD=wordpress
      - POSTGRES_DB=perfdata
    ports:
      - 5432:5432
  performancedatastorage:
    image: worldofjarcraft/performancedatastorage:latest
    container_name: performancedatastorage
    restart: always
    environment:
      MYSQL_HOST: db
    ports:
      - 6080:6080
  mosquitto:
    image:  worldofjarcraft/mosquitto:latest
    container_name: mosquitto
    ports:
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  requestgenerator:
    image:  worldofjarcraft/requestgenerator:latest
    container_name: requestgenerator
    restart: always
    volumes:
      - ../pdgf:/pdgf
      - ./pdgf-output:/output
    ports:
      - 8080:8080
    environment:
            - EXTRA_ARGUMENTS=--location http://localhost:8080 --bufferSize 1 --alternative-output-dir /output
    extra_hosts:
      - "users:172.22.17.255"
      - "posts:172.22.17.255"
      - "search:172.22.17.255"

  configui:
    image:  worldofjarcraft/configui:latest
    restart: always
    container_name: configui
    ports:
      - 3000:80
  pdgfui:
    image:  worldofjarcraft/pdgfui:latest
    restart: always
    container_name: pdgfui
    ports:
      - 3001:80

volumes:
  pg_data: {}
  mosquitto_data: {}
  mosquitto_log: {}

