version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wordpress
      - POSTGRES_PASSWORD=wordpress
      - POSTGRES_DB=perfdata
    ports:
      - 5432:5432
  performancedatastorage:
    image: performancedatastorage:latest
    restart: always
    ports:
      - 6080:6080
    environment:
      MYSQL_HOST: db
  mosquitto:
    image: eclipse-mosquitto:1.5
    volumes:
      - ./:/mosquitto/config/
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 9001:9001

  requestgenerator:
    image: requestgenerator:latest
    restart: always
    volumes:
      - ../pdgf:/pdgf
    links:
      - mosquitto:users

  conigui:
    image: configui:latest
    restart: always
    ports:
      - 3002:80
    environment:
      - REACT_APP_MQTT_HOST=users
      - REACT_APP_PDS_HOST=users:6080
      - REACT_APP_REQGEN_HOST=users:8080

volumes:
  pg_data: {}
  mosquitto_data: {}
  mosquitto_log: {}

